[project]
name = "de-project-group"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.0.0",
    "pandas>=2.3.2",
    "python-dotenv>=1.1.1",
    "tweepy>=4.16.0",
]
