steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/nasa-pipeline:latest'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/nasa-pipeline:latest'

images:
  - 'gcr.io/$PROJECT_ID/nasa-pipeline:latest'

# Build options
# Configure logging to only show in Cloud Logging (not in build output)
options:
  logging: CLOUD_LOGGING_ONLY
