steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/team-tinfoil/nasa-pipeline:latest'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/team-tinfoil/nasa-pipeline:latest'

images:
  - 'gcr.io/team-tinfoil/nasa-pipeline:latest'
